# Generated by Django 6.0.3 on 2026-05-31 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Family name or Client name', max_length=200)),
                ('location', models.CharField(blank=True, help_text='e.g., Koregaon Park, Pune', max_length=200)),
                ('content', models.TextField(verbose_name='Testimonial Text')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='happy_families/photos/')),
                ('video_file', models.FileField(blank=True, help_text='Upload testimonial video (MP4)', null=True, upload_to='happy_families/videos/')),
                ('document', models.FileField(blank=True, help_text='Optional appreciation letter/document', null=True, upload_to='happy_families/docs/')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Happy Family',
                'verbose_name_plural': 'Happy Families',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Enter requirements separated by new lines')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
