# Generated by Django 6.0.3 on 2026-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_price_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='construction_type',
            field=models.CharField(blank=True, help_text='e.g. Mivan Construction', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='total_land_parcel',
            field=models.CharField(blank=True, help_text='e.g. 5 Acres', max_length=100),
        ),
    ]
